# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from move_to_grab/LoopMoveToGrabMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import move_to_grab.msg
import geometry_msgs.msg
import std_msgs.msg

class LoopMoveToGrabMsg(genpy.Message):
  _md5sum = "8c0bfa85506ab2b9a3042cb471990b35"
  _type = "move_to_grab/LoopMoveToGrabMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """std_msgs/Bool isLoop
move_to_grab/MoveToGrabMsg action1
move_to_grab/MoveToGrabMsg action2

================================================================================
MSG: std_msgs/Bool
bool data
================================================================================
MSG: move_to_grab/MoveToGrabMsg
geometry_msgs/PoseStamped pose
std_msgs/Bool isSuckup
# std_msgs/Float32 backDistance 

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['isLoop','action1','action2']
  _slot_types = ['std_msgs/Bool','move_to_grab/MoveToGrabMsg','move_to_grab/MoveToGrabMsg']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       isLoop,action1,action2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LoopMoveToGrabMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.isLoop is None:
        self.isLoop = std_msgs.msg.Bool()
      if self.action1 is None:
        self.action1 = move_to_grab.msg.MoveToGrabMsg()
      if self.action2 is None:
        self.action2 = move_to_grab.msg.MoveToGrabMsg()
    else:
      self.isLoop = std_msgs.msg.Bool()
      self.action1 = move_to_grab.msg.MoveToGrabMsg()
      self.action2 = move_to_grab.msg.MoveToGrabMsg()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3I().pack(_x.isLoop.data, _x.action1.pose.header.seq, _x.action1.pose.header.stamp.secs, _x.action1.pose.header.stamp.nsecs))
      _x = self.action1.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7dB3I().pack(_x.action1.pose.pose.position.x, _x.action1.pose.pose.position.y, _x.action1.pose.pose.position.z, _x.action1.pose.pose.orientation.x, _x.action1.pose.pose.orientation.y, _x.action1.pose.pose.orientation.z, _x.action1.pose.pose.orientation.w, _x.action1.isSuckup.data, _x.action2.pose.header.seq, _x.action2.pose.header.stamp.secs, _x.action2.pose.header.stamp.nsecs))
      _x = self.action2.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7dB().pack(_x.action2.pose.pose.position.x, _x.action2.pose.pose.position.y, _x.action2.pose.pose.position.z, _x.action2.pose.pose.orientation.x, _x.action2.pose.pose.orientation.y, _x.action2.pose.pose.orientation.z, _x.action2.pose.pose.orientation.w, _x.action2.isSuckup.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.isLoop is None:
        self.isLoop = std_msgs.msg.Bool()
      if self.action1 is None:
        self.action1 = move_to_grab.msg.MoveToGrabMsg()
      if self.action2 is None:
        self.action2 = move_to_grab.msg.MoveToGrabMsg()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.isLoop.data, _x.action1.pose.header.seq, _x.action1.pose.header.stamp.secs, _x.action1.pose.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.isLoop.data = bool(self.isLoop.data)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action1.pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.action1.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 69
      (_x.action1.pose.pose.position.x, _x.action1.pose.pose.position.y, _x.action1.pose.pose.position.z, _x.action1.pose.pose.orientation.x, _x.action1.pose.pose.orientation.y, _x.action1.pose.pose.orientation.z, _x.action1.pose.pose.orientation.w, _x.action1.isSuckup.data, _x.action2.pose.header.seq, _x.action2.pose.header.stamp.secs, _x.action2.pose.header.stamp.nsecs,) = _get_struct_7dB3I().unpack(str[start:end])
      self.action1.isSuckup.data = bool(self.action1.isSuckup.data)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action2.pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.action2.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.action2.pose.pose.position.x, _x.action2.pose.pose.position.y, _x.action2.pose.pose.position.z, _x.action2.pose.pose.orientation.x, _x.action2.pose.pose.orientation.y, _x.action2.pose.pose.orientation.z, _x.action2.pose.pose.orientation.w, _x.action2.isSuckup.data,) = _get_struct_7dB().unpack(str[start:end])
      self.action2.isSuckup.data = bool(self.action2.isSuckup.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3I().pack(_x.isLoop.data, _x.action1.pose.header.seq, _x.action1.pose.header.stamp.secs, _x.action1.pose.header.stamp.nsecs))
      _x = self.action1.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7dB3I().pack(_x.action1.pose.pose.position.x, _x.action1.pose.pose.position.y, _x.action1.pose.pose.position.z, _x.action1.pose.pose.orientation.x, _x.action1.pose.pose.orientation.y, _x.action1.pose.pose.orientation.z, _x.action1.pose.pose.orientation.w, _x.action1.isSuckup.data, _x.action2.pose.header.seq, _x.action2.pose.header.stamp.secs, _x.action2.pose.header.stamp.nsecs))
      _x = self.action2.pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_7dB().pack(_x.action2.pose.pose.position.x, _x.action2.pose.pose.position.y, _x.action2.pose.pose.position.z, _x.action2.pose.pose.orientation.x, _x.action2.pose.pose.orientation.y, _x.action2.pose.pose.orientation.z, _x.action2.pose.pose.orientation.w, _x.action2.isSuckup.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.isLoop is None:
        self.isLoop = std_msgs.msg.Bool()
      if self.action1 is None:
        self.action1 = move_to_grab.msg.MoveToGrabMsg()
      if self.action2 is None:
        self.action2 = move_to_grab.msg.MoveToGrabMsg()
      end = 0
      _x = self
      start = end
      end += 13
      (_x.isLoop.data, _x.action1.pose.header.seq, _x.action1.pose.header.stamp.secs, _x.action1.pose.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      self.isLoop.data = bool(self.isLoop.data)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action1.pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.action1.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 69
      (_x.action1.pose.pose.position.x, _x.action1.pose.pose.position.y, _x.action1.pose.pose.position.z, _x.action1.pose.pose.orientation.x, _x.action1.pose.pose.orientation.y, _x.action1.pose.pose.orientation.z, _x.action1.pose.pose.orientation.w, _x.action1.isSuckup.data, _x.action2.pose.header.seq, _x.action2.pose.header.stamp.secs, _x.action2.pose.header.stamp.nsecs,) = _get_struct_7dB3I().unpack(str[start:end])
      self.action1.isSuckup.data = bool(self.action1.isSuckup.data)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.action2.pose.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.action2.pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.action2.pose.pose.position.x, _x.action2.pose.pose.position.y, _x.action2.pose.pose.position.z, _x.action2.pose.pose.orientation.x, _x.action2.pose.pose.orientation.y, _x.action2.pose.pose.orientation.z, _x.action2.pose.pose.orientation.w, _x.action2.isSuckup.data,) = _get_struct_7dB().unpack(str[start:end])
      self.action2.isSuckup.data = bool(self.action2.isSuckup.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7dB = None
def _get_struct_7dB():
    global _struct_7dB
    if _struct_7dB is None:
        _struct_7dB = struct.Struct("<7dB")
    return _struct_7dB
_struct_7dB3I = None
def _get_struct_7dB3I():
    global _struct_7dB3I
    if _struct_7dB3I is None:
        _struct_7dB3I = struct.Struct("<7dB3I")
    return _struct_7dB3I
_struct_B3I = None
def _get_struct_B3I():
    global _struct_B3I
    if _struct_B3I is None:
        _struct_B3I = struct.Struct("<B3I")
    return _struct_B3I
